meta_product_name: "Visite Arraial do Cabo"
meta_title: "Visite Arraial do Cabo - The real paradise!"
meta_description: "The best guide that you can find to plan your trip to Arraial do Cabo"
meta_image: "cover.jpg" # should exist in `app/assets/images/`
